version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.16.1
    commands:
      - ls -la
      - echo installing "node modules
      - yarn install 

  pre_build:
  install:
    commands:
      - npm install -g yarn
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - yarn
    commands:
      - echo Installing source NPM dependiencies ...
      - yarn build 
      - ls -la
  post_build:
    commands:
      - echo Deployment completed on `date`
artifacts:
    files:
      - '**/*'
    base-directory: 'build'
